task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from registration.backends.simple.views import RegistrationView


urlpatterns = [
    path(r'accounts/', include('registration.backends.simple.urls')),
    path('', include('tm.urls')),
    path('admin/', admin.site.urls),
]

task_manager/tm/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from registration.backends.simple.views import RegistrationView
from . import views
from . import forms

urlpatterns = [
    path(r'signup/', RegistrationView.as_view(form_class=forms.MyRegistrationForm), name='register'),
    path(r'login/', LoginView.as_view(form_class=forms.LoginForm), name='login'),
    path(r'logout/', views.mylogout, name='logout'),
    path(r'change_task/', views.change_task, name='change_task'),
    path(r'new_task/', views.new_task, name='new_task'),
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'task/<int:id>/', views.task, name='task'),
]

task_manager/tm/models.py
from django.db import models
from django.contrib.auth.models import User
import django_filters

STATUS_CHOICES = {
    (0, 'Open'),
    (1, 'Pending for approval'),
    (2, 'Closed'),
}

PRIORITY_CHOICES = {
    (0, 'Low'),
    (1, 'Medium'),
    (2, 'High')
}

class Task(models.Model):
    deadline = models.DateTimeField('DeadLine')
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mytask')
    executor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='task')
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=1)  # 0 - low, 1 - medium, 2 - high
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)  # 0 - open, 1 - pending for approval, 2 - closed

    def __str__(self):
        return '\n'.join([
            'Task#{} {}'.format(self.id, self.title),
            'Deadline: {}'.format(self.deadline),
            ('Closed' if self.status == 2 else 'Pending for approval' if self.status else 'Open'),
        ])


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comment')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment')
    published = models.DateTimeField('published')
    text = models.CharField(max_length=500)

    def __str__(self):
        return "Comment#{} to {} by {}".format(str(self.id), self.task.title, self.author.get_full_name())

task_manager/tm/forms.py
from django import forms
from datetime import datetime
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from registration.forms import RegistrationForm
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now
from .models import Comment


class ChangeCommentForm(forms.Form):
    comment_edit_text = forms.CharField(max_length=500, required=True)
    cid = forms.IntegerField


class CommentForm(forms.ModelForm):
    text = forms.CharField(max_length=500, required=True, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'id': 'comment_text_form',
    }))

    class Meta:
        model = Comment
        fields = ['text']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=150, label=_('Username'), required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=100, label=_('Password'), required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'name': "password1",
                                                             'type': "password"}))


class MyRegistrationForm(RegistrationForm):
    username = forms.CharField(max_length=150, label=_('Username'), required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=30, label=_('First name'), required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=150, label=_('Last name'), required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=254, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(max_length=100, label=_('Password'), required=True,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'name': "password1",
                                                              'type': "password"}))
    password2 = forms.CharField(max_length=100, label=_('Repeat your password'), required=True,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'name': "password2",
                                                              'type': "password"}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']
        widgets = {'username': forms.TextInput(attrs={'class': 'form-control'})}


class NewTaskForm(forms.Form):
    title = forms.CharField(label='Title: ', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    deadline_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
    deadline_time = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control'}))
    priority = forms.ChoiceField(label='Priority: ', choices=[
        (0, 'Low'),
        (1, 'Medium'),
        (2, 'High'),
    ], widget=forms.Select(attrs={'class': 'form-control'}))
    description = forms.CharField(label='Description: ', max_length=500, widget=forms.Textarea(attrs={
        'class': 'form-control'
    }))
    executor = forms.ChoiceField(label='Executor: ', choices=[
        (user.id, user.get_full_name()) for user in User.objects.all() if user.id > 1
    ], widget=forms.Select(attrs={'class': 'form-control'}))

task_manager/tm/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseForbidden, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.utils.dateparse import parse_date, parse_time
from .models import Task, Comment
from datetime import datetime
from .forms import NewTaskForm, CommentForm, ChangeCommentForm
from django.utils.timezone import now
from django_filters.views import FilterView
from .filters import IndexFilter


class IndexView(FilterView):
    template_name = 'tm/index.html'
    model = Task
    paginate_by = 2
    filterset_class = IndexFilter


def mylogout(req):
    logout(req)
    return redirect('/login')


@login_required
def change_task(req):
    if req.method == 'GET':
        return HttpResponseForbidden('Only POST methods are accepted')
    task = None
    try:
        task = get_object_or_404(Task, id=int(req.POST['id']))
    except KeyError:
        return HttpResponseBadRequest('Necessary argument \"id\" not passed')
    if req.POST['submit'] == 'delete':
        if req.user == task.author:
            task.delete()
            return redirect('/')
        else:
            return HttpResponseForbidden('Only author can delete the task')
    if req.POST['submit'] == 'change':
        if req.user == task.author:
            task.description = req.POST['description']
            task.executor = User.objects.get(id=int(req.POST['executor']))
            task.priority = int(req.POST['priority'])
            task.deadline = datetime.combine(parse_date(req.POST['deadline_date']), parse_time(req.POST['deadline_time']))
        if req.user == task.author or req.user == task.executor:
            task.status = int(req.POST['status'])
        task.save()
        return redirect('/task/{}'.format(req.POST['id']))
    return HttpResponseBadRequest('Invalid submit parameter')


@login_required
def new_task(req):
    if req.method == "POST":
        form = NewTaskForm(req.POST)
        if form.is_valid():
            id = Task.objects.create(
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                author=req.user,
                executor=User.objects.get(id=form.cleaned_data['executor']),
                priority=form.cleaned_data['priority'],
                status=0,
                deadline=datetime.combine(form.cleaned_data['deadline_date'], form.cleaned_data['deadline_time'])
            ).id
            return redirect('/task/{}/'.format(id))
        return HttpResponseBadRequest('Invalid request passed')
    elif req.method == 'GET':
        return render(req, 'tm/new_task.html', {'form': NewTaskForm({'executor': req.user.id, 'priority': 1})})


@login_required
def task(req, id):
    task = get_object_or_404(Task, id=id)
    if req.method == 'POST':
        if req.POST['submit'] == 'comment':
            form = CommentForm(req.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = req.user
                comment.task = task
                comment.published = now()
                comment.save()
        elif req.POST['submit'] == 'edit_comment':
            form = ChangeCommentForm(req.POST)
            if form.is_valid():
                comment = get_object_or_404(Comment, id=req.POST['cid'])
                comment.text = req.POST['comment_edit_text']
                comment.save()
        elif req.POST['submit'] == 'delete_comment':
            get_object_or_404(Comment, id=req.POST['cid']).delete()

        return redirect('/task/' + str(task.id))

    return render(req, 'tm/task.html', {
        'task': task,
        'priority': 'High' if task.priority == 2 else 'Medium' if task.priority else 'Low',
        'status': ('Closed' if task.status == 2 else 'Pending for approval' if task.status else 'Open'),
        'author': task.author,
        'executor': task.executor,
        'executors': User.objects.all(),
        'comment_form': CommentForm,
        'change_comment_form': ChangeCommentForm,
        'comments': task.comment.extra(order_by=['-published'])
    })

task_manager/tm/templates/tm/index.html
{% extends "base.html" %}
{% load task_manager_extra %}
{% load static %}
{% block headers %}
<link rel="stylesheet" href="{% static 'tm/index.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
{% endblock %}
{% block content %}
<form method="get" action="{% url 'index' %}?"
      style="margin-left: 5rem">
    <table>
        <tr>
            <td class="pretty p-switch p-fill">
                <input type="checkbox" name="with_my_comment" id="id_with_my_comment" value="true"
                       {% if request.GET.with_my_comment %} checked {% endif %}>
                <div class="state p-primary switcher">
                    <label for="id_with_my_comment">Tasks with my comments</label>
                </div>
            </td>
            <td class="pretty p-switch p-fill">
                <input type="checkbox" name="my_tasks" id="id_my_tasks" value="true" {% if request.GET.my_tasks %} checked {% endif %}>
                <div class="state p-primary switcher">
                    <label for="id_my_tasks">My tasks</label>
                </div>
            </td>
            <td class="pretty p-switch p-fill">
                <input type="checkbox" name="me_executor" id="id_me_executor" value="true"
                       {% if request.GET.me_executor %} checked {% endif %}>
                <div class="state p-primary switcher">
                    <label for="id_me_executor">Me executor</label>
                </div>
            </td>
            <td class="pretty p-switch p-fill">
            <input type="checkbox" name="over_due" autocomplete="off" id="id_over_due" value="true"
                   {% if request.GET.over_due %} checked {% endif %}>
            <div class="state p-primary switcher">
                <label for="id_over_due">Over due</label>
            </div>
            </td>
            <td>
                <label for="id_status"> Status: </label>
            </td>
            <td>
                {{ filter.form.status }}
            </td>
            <td>
                <label for="id_priority" id="priority_label"> Priority:</label>
            </td>
            <td>
                {{ filter.form.priority }}
            </td>
            <td>
                <button class="btn btn-success" type="submit" id="index_filter_submit" style="margin-left: 2rem">
                    Filter
                </button>
            </td>
        </tr>
    </table>
</form>
<hr>
<div id="tasks" style="margin-left: 5rem;">
    {% for task in object_list %}
    <h1>
        <a href="{% url 'task' task.id %}">{{ task.title }}</a>
    </h1>
    <p>Deadline: {{ task.deadline }}</p>
    <p>Priority:
        {{ task.get_priority_display }}
    </p>
    <p>Status:
        {{ task.get_status_display }}
    </p>
    <hr>
    {% endfor %}
</div>
<div class="page_nav">
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="?{% url_replace page=page_obj.previous_page_number %}" id="prev_page_link" class="btn btn-outline-primary">Previous page</a>
    {% endif %}
    {% if page_obj.has_next %}
    <a href="?{% url_replace page=page_obj.next_page_number %}" id="next_page_link" class="btn btn-outline-primary">Next page</a>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

task_manager/tm/templates/tm/new_task.html
{% extends "base.html" %}

{% block title %}
New Task
{% endblock %}

{% block headers %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tm/new_task.css' %}">
{% endblock %}

{% block content %}
<h1 style="margin-left: 2rem">Create a new task:</h1>
{% for error in errors %}
<p style="color:red">{{ error }}</p>
{% endfor %}
<form method="POST" action="{% url 'new_task' %}" id="main_form">
    {% csrf_token %}
    <div style="margin: 0 auto">
    <table>
        <tr>
            <td>{{ form.title.label }}</td><td>{{ form.title }}</td>
        </tr>
        <tr>
            <td><label for="id_deadline_date">
                <label for="id_deadline_time">Deadline: </label>
            </label></td>
            <td>
                <input type="date" name="deadline_date" id="id_deadline_date" value="{% now 'Y-m-d' %}" class="form-control" />
                <input type="time" name="deadline_time" id="id_deadline_time" value="{% now 'H:i' %}" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>{{ form.priority.label }}</td><td> {{ form.priority }}</td>
        </tr>
        <tr>
            <td>{{ form.description.label }}</td><td>{{ form.description }}</td>
        </tr>
        <tr>
            <td>{{ form.executor.label }}</td><td>{{ form.executor }}</td>
        </tr>
    </table>
    </div>
    <input type="submit" value="Create a new task!" class="btn btn-success" />
</form>

{% endblock %}

task_manager/tm/templates/tm/task.html
{% extends "base.html" %}

{% block headers %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'task_style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'tm/comments.css' %}">
{% endblock %}

{% block title %}
{{ task.title }}
{% endblock %}

{% block content %}
<h1 style="margin-left: 5rem; margin-top: 2rem">{{ task.title }}</h1>
<table>
    <tr><td><h4>Deadline: </h4></td>
        {% if author == user %}
        <td>
            <input class="form-control" name="deadline_date" form="change_task_form" type="date" style="width:10rem !important;float: left"
                   value="{{ task.deadline|date:"Y-m-d"}}" />
            <input class="form-control" name="deadline_time" form="change_task_form" type="time" style="width:6rem !important;float:right"
                   value="{{ task.deadline|time:"H:i" }}" />
        </td>
        {% else %}
        <td style>{{ task.deadline }}</td>
        {% endif %}
    </tr>
    <tr>
        <td>Priority: </td>
        {% if author == user %}
        <td>
            <form action="{% url 'change_task' %}" id="change_task_form" method="POST">
                {% csrf_token %}
                <select name="priority" class="form-control">
                    <option value="0" {% ifequal  task.priority 0 %} selected {% endifequal %} >Low</option>
                    <option value="1" {% ifequal  task.priority 1 %} selected {% endifequal %}>Medium</option>
                    <option value="2" {% ifequal  task.priority 2 %} selected {% endifequal %}>High</option>
                </select>
                <input type="hidden" name="id" value="{{ task.id }}" />
            </form>
        </td>
        {% else %}
        <td> {{ priority }}</td>
        {% endif %}
    </tr>
    <tr>
        <td>Status: </td>
        <td>
            {% if author == user or executor == user%}
            <select name="status" form="change_task_form" class="form-control" style="width: 20rem !important;">
                <option value="0" {% ifequal  task.status 0 %} selected {% endifequal %} >Open</option>
                <option value="1" {% ifequal  task.status 1 %} selected {% endifequal %}>Pending for approval</option>
                {% if author == user %}
                <option value="2" {% ifequal  task.status 2 %} selected {% endifequal %}>Closed</option>
                {% endif %}
            </select>
            {% else %}
            {{ status }}
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>
            {% ifequal task.status 0 %}
            Must be solved
            {% else %}
            Solved
            {% endifequal %}
            by
        </td>
        <td>
            {% if author == user and task.status == 0 %}
            <select name="executor" form="change_task_form" class="form-control">
                {% for exec in executors %}
                {% if exec.id > 1 %}
                <option value="{{ exec.id }}" {% if exec == executor %} selected {% endif %}>
                    {{ exec.get_full_name }}
                </option>
                {% endif %}
                {% endfor %}
            </select>
            {% else %}
            {{ executor.get_full_name }}
            {% endif %}
        </td>
    </tr>
</table>
{% if author == user %}
<textarea form="change_task_form" rows="6" cols="50" name="description" class="form-control" id="change_descr">{{ task.description }}</textarea>
{% else %}
<p style="margin-left: 5rem">{{ task.description }}</p>
{% endif %}
{% if author == user or executor == user %}
<table style="margin-left: 5rem">
    <tr>
        <td>
            <button type="submit" value="change" name="submit" class="btn btn-success"  form="change_task_form" id="change_task_form_button">
                Change task
            </button>
        </td>
        <td>
            {% if author == user %}
            <button type="submit" value="delete" name="submit" class="btn btn-danger" form="change_task_form" >
                Delete task
            </button>
            {% endif %}
        </td>
    </tr>
</table>
{% endif %}
<p style="margin-left: 5rem">Stated by {{ author.get_full_name }}</p>
<br>
<br>
<p><h2 style="margin-left: 5rem">Feel free to comment:</h2></p>
<table id="comment_table">
    <tr>
        <td>
            <form method="post">
                {% csrf_token %}
                {{ comment_form.text }}
                <button type="submit" name="submit" class="btn btn-dark" value="comment" id="comment_submit">
                    Comment
                </button>
            </form>
        </td>
    </tr>
    {% for comment in comments %}
    <tr>
        <td>
            <div class="comment_info">
                <p><h3>{{ comment.author.get_full_name }}</h3></p>
                <p>{{ comment.published }}</p>
            </div>
            {% if comment.author == user %}
            <div class="comment_change_buttons">
                <form method="POST" action="{% url 'task' id=task.id %}" id="comment_{{ comment.id }}_change_form">
                    {% csrf_token %}
                    <div class="comment_delete_button"><button type="submit" name="submit" value="delete_comment" class="btn btn-outline-danger">
                        Delete
                    </button></div>
                    <div class="comment_edit_button"><button type="submit" name="submit" value="edit_comment" class="btn btn-outline-success">
                        Edit
                    </button></div>
                    <input type="hidden" id="id_cid" name="cid" value="{{ comment.id }}" />
                </form>
            </div>
            {% endif %}
        </td>
        <td>
            {% if comment.author == user %}
            <textarea name="comment_edit_text" id="id_comment_edit_text" class="form-control"
                      form="comment_{{ comment.id }}_change_form">{{ comment.text }}</textarea>
            {% else %}
            {{ comment.text }}
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

task_manager/tm/templates/tm/testindex.html
{% extends "base.html" %}
{% block headers %}
<style>
    #id_status {
        width: 15rem !important;
    }
    div.switcher {
        margin-top: 0.15rem !important;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
{% endblock %}
{% block content %}
<form method="get" action="{% url 'testindex' %}" style="margin-left: 5rem">
    <table>
        <tr>
            <td class="pretty p-switch p-fill">
                <input type="checkbox" name="with_my_comment" id="id_with_my_comment" value="true">
                <div class="state p-primary switcher">
                    <label for="id_with_my_comment">Tasks with my comments</label>
                </div>
            </td>
            <td class="pretty p-switch p-fill">
                <input type="checkbox" name="my_tasks" id="id_my_tasks" value="true">
                <div class="state p-primary switcher">
                    <label for="id_my_tasks">My tasks</label>
                </div>
            </td>
            <td class="pretty p-switch p-fill">
                <input type="checkbox" name="me_executor" id="id_me_executor" value="true">
                <div class="state p-primary switcher">
                    <label for="id_me_executor">Me executor</label>
                </div>
            </td>
            <td class="pretty p-switch p-fill">
            <input type="checkbox" name="over_due" autocomplete="off" id="id_over_due" value="true">
            <div class="state p-primary switcher">
                <label for="id_over_due">Over due</label>
            </div>
            </td>
            <td>
                <label for="id_status"> Status: </label>
            </td>
            <td>
                {{ filter.form.status }}
            </td>
            <td>
                <button class="btn btn-success" type="submit" id="index_filter_submit" style="margin-left: 2rem">
                    Filter
                </button>
            </td>
        </tr>
    </table>
</form>
<hr>
<div id="tasks" style="margin-left: 5rem;">
    {% for task in filter.qs %}
    <h1>
        <a href="{% url 'task' task.id %}">{{ task.title }}</a>
    </h1>
    <p>Deadline: {{ task.deadline }}</p>
    <p>Priority:
        {{ task.get_priority_display }}
    </p>
    <p>Status:
        {{ task.get_status_display }}
    </p>
    <hr>
    {% endfor %}
</div>
{% endblock %}